// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_Animation800x480();
Q_GHS_KEEP_REFERENCE(qml_register_types_Animation800x480)

class Animation800x480Plugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    Animation800x480Plugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_Animation800x480;
        Q_UNUSED(registration)
    }
};



#include "Animation800x480plugin_Animation800x480Plugin.moc"
